src/main/java/pt/opensoft/jsfprototype/model/Declaracao.java
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 10:48:02 PM WEST 
//


package pt.opensoft.jsfprototype.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Rosto">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QuadroInicial">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="titular" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Quadro1">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dataRececao" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AnexoA" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Quadro1">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="percentagem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Quadro2">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="valor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rosto",
    "anexoA"
})
@XmlRootElement(name = "Declaracao")
public class Declaracao {

    @XmlElement(name = "Rosto", required = true)
    protected Rosto rosto;
    @XmlElement(name = "AnexoA")
    protected AnexoA anexoA;

    /**
     * Gets the value of the rosto property.
     * 
     * @return
     *     possible object is
     *     {@link pt.opensoft.jsfprototype.model.Declaracao.Rosto }
     *     
     */
    public Rosto getRosto() {
        return rosto;
    }

    /**
     * Sets the value of the rosto property.
     * 
     * @param value
     *     allowed object is
     *     {@link pt.opensoft.jsfprototype.model.Declaracao.Rosto }
     *     
     */
    public void setRosto(Rosto value) {
        this.rosto = value;
    }

    /**
     * Gets the value of the anexoA property.
     * 
     * @return
     *     possible object is
     *     {@link pt.opensoft.jsfprototype.model.Declaracao.AnexoA }
     *     
     */
    public AnexoA getAnexoA() {
        return anexoA;
    }

    /**
     * Sets the value of the anexoA property.
     * 
     * @param value
     *     allowed object is
     *     {@link pt.opensoft.jsfprototype.model.Declaracao.AnexoA }
     *     
     */
    public void setAnexoA(AnexoA value) {
        this.anexoA = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Quadro1">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="percentagem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Quadro2">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="valor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "quadro1",
        "quadro2"
    })
    public static class AnexoA {

        @XmlElement(name = "Quadro1", required = true)
        protected Quadro1 quadro1;
        @XmlElement(name = "Quadro2", required = true)
        protected Quadro2 quadro2;

        /**
         * Gets the value of the quadro1 property.
         * 
         * @return
         *     possible object is
         *     {@link pt.opensoft.jsfprototype.model.Declaracao.AnexoA.Quadro1 }
         *     
         */
        public Quadro1 getQuadro1() {
            return quadro1;
        }

        /**
         * Sets the value of the quadro1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link pt.opensoft.jsfprototype.model.Declaracao.AnexoA.Quadro1 }
         *     
         */
        public void setQuadro1(Quadro1 value) {
            this.quadro1 = value;
        }

        /**
         * Gets the value of the quadro2 property.
         * 
         * @return
         *     possible object is
         *     {@link pt.opensoft.jsfprototype.model.Declaracao.AnexoA.Quadro2 }
         *     
         */
        public Quadro2 getQuadro2() {
            return quadro2;
        }

        /**
         * Sets the value of the quadro2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link pt.opensoft.jsfprototype.model.Declaracao.AnexoA.Quadro2 }
         *     
         */
        public void setQuadro2(Quadro2 value) {
            this.quadro2 = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="percentagem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "percentagem"
        })
        public static class Quadro1 {

            protected String percentagem;

            /**
             * Gets the value of the percentagem property.
             * 
             * @return
             *     possible object is
             *     {@link String }

src/main/java/pt/opensoft/jsfprototype/model/package-info.java
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 10:48:02 PM WEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pt.opensoft.jsfprototype", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pt.opensoft.jsfprototype.model;

src/main/java/pt/opensoft/jsfprototype/managedController/DeclaracaoManagedBean.java
package pt.opensoft.jsfprototype.managedController;
 
import java.io.Serializable;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.xml.bind.JAXBException;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import pt.opensoft.jsfprototype.model.Declaracao;
import pt.opensoft.jsfprototype.service.DeclaracaoService;

@ManagedBean(name="declaracaoMB")
@ViewScoped
public class DeclaracaoManagedBean implements Serializable {
 
    private static final long serialVersionUID = 1L;
    private static final Logger logger = Logger.getLogger((DeclaracaoManagedBean.class.getSimpleName()));

    @ManagedProperty(value="#{DeclaracaoService}")
    DeclaracaoService declaracaoService;

    private Declaracao declaracao;

    public DeclaracaoManagedBean() {
        logger.info("Foi contruído o  DeclaracaoManagedBean");
    }

    public void submete() {
        logger.info("Foi invocado o submete");
        try {
            String error = getDeclaracaoService().submete(declaracao);
            if (error != null) {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error!", error));
            } else {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "A declaração foi submetida com sucesso"));
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, e.getMessage(), e);
        }
 
    }

    public void valida() {
        logger.info("Foi invocado o valida");
        try {
            String error = getDeclaracaoService().valida(declaracao);
            if (error != null) {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error!", error));
            } else {
                FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", "A declaração está correta"));
            }
        } catch (Exception e) {
            logger.log(Level.SEVERE, e.getMessage(), e);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, "Fatal!", "System Error"));
        }
    }

    public DeclaracaoService getDeclaracaoService() {
        return declaracaoService;
    }

    public void setDeclaracaoService(DeclaracaoService declaracaoService) {
        this.declaracaoService = declaracaoService;
    }

    public Declaracao getDeclaracao() {
        logger.info("Foi invocado o getDeclaracao");
        return declaracao;
    }

    public String getLoadDeclaracao() throws JAXBException {
        logger.info("Foi invocado o loadDeclaracao");
        Map<String,String> params =
                FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String action = params.get("action");
        logger.info(action);
        if (action != null && action.equals("pp")) {
            declaracao = getDeclaracaoService().getPP();
        } else {
            declaracao = getDeclaracaoService().getNova();
        }

        return "";
    }

    public String redirect()  {
        logger.info("Foi invocado o redirect");
        Map<String,String> params =
                FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        String action = params.get("action");
        logger.info(action);
        if (action != null && action.equals("pp")) {
            return "index";
        } else {
            return "index";
        }

    }

    public void removeAnexoA() {
        logger.info("Foi invocado o removeAnexoA");
        declaracao.setAnexoA(null);
    }

    public void criaAnexoA() {
        logger.info("Foi invocado o criaAnexoA");
        declaracao.setAnexoA(new Declaracao.AnexoA());
        declaracao.getAnexoA().setQuadro1(new Declaracao.AnexoA.Quadro1());
        declaracao.getAnexoA().setQuadro2(new Declaracao.AnexoA.Quadro2());
    }


    public void setRostoQuadro1DataRececao(Date dataRececao) throws DatatypeConfigurationException {
        logger.info("Foi invocado o setRostoQuadro1DataRececao");
        if (dataRececao == null) {
            declaracao.getRosto().getQuadro1().setDataRececao(null);
        } else {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            logger.info("data antes de colocar no xml: df.format(dataRececao)");
            declaracao.getRosto().getQuadro1().setDataRececao(df.format(dataRececao));
        }
    }

    public Date getRostoQuadro1DataRececao() throws ParseException {
        logger.info("Foi invocado o getRostoQuadro1DataRececao");
        Date result = null;
        if (declaracao.getRosto().getQuadro1().getDataRececao() != null && !declaracao.getRosto().getQuadro1().getDataRececao().isEmpty()) {
            logger.info("data como veio do xml: " + declaracao.getRosto().getQuadro1().getDataRececao());
            result = new SimpleDateFormat("yyyy-MM-dd").parse(declaracao.getRosto().getQuadro1().getDataRececao());
        }
        return result;
    }

    public Double getAnexoAQuadro2Valor() {
        logger.info("Foi invocado o getAnexoAQuadro2Valor");
        Double result = null;
        if (declaracao.getAnexoA().getQuadro2().getValor() != null && !declaracao.getAnexoA().getQuadro2().getValor().isEmpty()) {
            result = new Double(declaracao.getAnexoA().getQuadro2().getValor()) / 100;
        }
        return result;
    }

    public void setAnexoAQuadro2Valor(Double valor) {
        logger.info("Foi invocado o setRostoQuadro1DataRececao");
        if (valor == null || valor.equals(Double.parseDouble("0"))) {
            declaracao.getAnexoA().getQuadro2().setValor(null);
        } else {
            declaracao.getAnexoA().getQuadro2().setValor(((long) (valor * 100)) + "");
        }
    }
}

src/main/webapp/index.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions">
<h:head><title>T5K</title></h:head>
<h:body>
    <h:form id="formulario">
        <!-- TODO deveria usar o remote comand? -->
        <h:outputText value="#{declaracaoMB.loadDeclaracao}"></h:outputText>
        <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" globalOnly="true"/>
        <p:panel header="Declaração" id="declaracao">
            <p:commandButton id="adicionaAnexoA" value="Cria Anexo A" action="#{declaracaoMB.criaAnexoA}" ajax="true" update="declaracao" rendered="#{declaracaoMB.declaracao.anexoA == null}" validateClient="false" immediate="true"/>
            <p:commandButton id="removeAnexoA" value="Remove Anexo A" action="#{declaracaoMB.removeAnexoA}" ajax="true" update="declaracao" rendered="#{declaracaoMB.declaracao.anexoA != null}" validateClient="false" immediate="true"/>
            <p:tabView orientation="left" id="tabsAnexos">
                <p:tab title="Rosto" id="tabRosto">
                <p:tabView id="tabQuadros">
                        <p:tab title="Quadro Inicial" id="tabInicial">
                            <h:panelGrid id="grid1" columns="3" cellpadding="5">
                                <h:outputLabel for="nif" value="NIF : " />
                                <p:inputMask id="nif" value="#{declaracaoMB.declaracao.rosto.quadroInicial.titular}" mask="999999999" required="true" requiredMessage="Obrigatório"/>
                                <p:message for="nif" />

                                <h:outputLabel for="email" value="Email : " />
                                <p:inputText id="email" value="#{declaracaoMB.declaracao.rosto.quadroInicial.email}" required="true" requiredMessage="Obrigatório">
                                    <f:validateRegex pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
                                </p:inputText>
                                <p:message for="email" />
                            </h:panelGrid>
                        </p:tab>
                        <p:tab title="Quadro 1">
                            <h:panelGrid columns="3" cellpadding="5">
                                <h:outputLabel for="dataRececao" value="Data : " />
                                <p:calendar id="dataRececao" value="#{declaracaoMB.rostoQuadro1DataRececao}" showOn="button" pattern="yyyy-MM-dd">
                                </p:calendar>
                                <p:message id="dataRececaoMsg" for="dataRececao" display="icon"/>
                            </h:panelGrid>
                        </p:tab>
                    </p:tabView>
                </p:tab>
                <p:tab title="Anexo A" rendered="#{declaracaoMB.declaracao.anexoA != null}">
                    <p:tabView>
                        <p:tab title="Quadro 1">
                            <h:panelGrid columns="3" cellpadding="5">
                                <h:outputLabel for="percentagem" value="Percentagem (%): " />
                                <p:spinner id="percentagem" value="#{declaracaoMB.declaracao.anexoA.quadro1.percentagem}" min="0" max="100"/>
                                <p:message id="percentagemMsg" for="percentagem" display="icon"/>
                            </h:panelGrid>
                        </p:tab>
                        <p:tab title="Quadro 2">
                            <h:panelGrid columns="3" cellpadding="5">
                                <h:outputLabel for="valor" value="Valor (€): " />
                                <pe:inputNumber id="valor" value="#{declaracaoMB.anexoAQuadro2Valor}" symbol=" €" symbolPosition="s"
                                                decimalSeparator="," thousandSeparator="." emptyValue="empty"/>
                                <!--p:inputMask id="valor" value="#{declaracaoMB.declaracao.anexoA.quadro2.valor}" mask="99999999?"/-->
                                <!--p:inputText id="valor" value="#{declaracaoMB.declaracao.anexoA.quadro2.valor}">
                                    <f:converter converterId="javax.faces.Integer"/>
                                </p:inputText-->
                                <p:message id="valorMsg" for="valor" display="icon"/>
                            </h:panelGrid>
                        </p:tab>
                    </p:tabView>
                </p:tab>
            </p:tabView>
        </p:panel>




        <p:commandButton id="submete" value="Submete" action="#{declaracaoMB.submete}" ajax="true" validateClient="true" update="declaracao"/>
        <p:commandButton id="valida" value="Valida" action="#{declaracaoMB.valida}" ajax="true" validateClient="true" update="declaracao"/>

        <p:commandButton id="pp" value="Pré-preenche" action="#{declaracaoMB.redirect}" ajax="false" validateClient="false" immediate="true">
                <f:param name="action" value="pp" />
        </p:commandButton>


        <p:commandButton id="novo" value="Novo" action="#{declaracaoMB.redirect}" ajax="false" validateClient="false" immediate="true">
        </p:commandButton>


    </h:form>
</h:body>
</html> 